"""
agent.py - Simplified LangGraph Agentic Workflow
"""
import os
from typing import TypedDict, Optional, List
from langchain_groq import ChatGroq
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, END

# === Configuration ===
_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CHROMA_DB_PATH = os.path.join(_BASE_DIR, "chroma_db")
EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
LLM_MODEL = "llama-3.3-70b-versatile"

# === Agent State ===
class HealthAgentState(TypedDict):
    patient_summary: str
    risk_score: float
    prediction_label: str
    prediction_confidence: float
    groq_api_key: str
    retrieved_guidelines: List[str]
    health_report: Optional[str]

# === Prompt Template ===
REPORT_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a knowledgeable and empathetic AI health support assistant.
CRITICAL RULES:
- Only make claims that are supported by the provided guidelines.
- NEVER invent statistics or drug names.
- Always recommend consulting a healthcare professional.
- Structure your response EXACTLY as instructed."""),
    ("human", """
## Patient Risk Assessment
- **ML Risk Score**: {risk_score:.1f} / 100
- **Prediction**: {prediction_label} (Confidence: {confidence:.1f}%)
- **Patient Profile**: {patient_summary}

## Retrieved Medical Guidelines 
{guidelines_text}

---
Please generate a **Structured Health Report** in markdown format with exactly these sections:
### 🧬 Risk Summary
### ⚠️ Key Risk Factors Identified
### 💡 Personalized Recommendations
### 📅 Follow-Up Actions
### 📚 Sources
### ⚕️ Medical Disclaimer
> Include a disclaimer that this report is generated by an AI for informational purposes only.
""")
])

# === Nodes ===
def retrieve_guidelines(state: HealthAgentState) -> HealthAgentState:
    try:
        embeddings = HuggingFaceEmbeddings(model_name=EMBED_MODEL)
        vectorstore = Chroma(persist_directory=CHROMA_DB_PATH, embedding_function=embeddings)
        
        query = f"Diabetes guidelines for a patient with risk score {state['risk_score']:.1f}, predicted as {state['prediction_label']}."
        results = vectorstore.similarity_search(query, k=5)
        
        return {**state, "retrieved_guidelines": [doc.page_content for doc in results]}
    except Exception as e:
        print(f"Retrieval error: {e}")
        return {**state, "retrieved_guidelines": []}

def generate_report(state: HealthAgentState) -> HealthAgentState:
    try:
        llm = ChatGroq(model=LLM_MODEL, temperature=0.3, groq_api_key=state["groq_api_key"])
        
        guidelines_text = "\n\n---\n\n".join(state["retrieved_guidelines"]) if state["retrieved_guidelines"] else "No specific guidelines retrieved."
        
        chain = REPORT_PROMPT | llm
        response = chain.invoke({
            "risk_score": state["risk_score"],
            "prediction_label": state["prediction_label"],
            "confidence": state["prediction_confidence"],
            "patient_summary": state["patient_summary"],
            "guidelines_text": guidelines_text,
        })
        
        return {**state, "health_report": response.content}
    except Exception as e:
        return {**state, "health_report": f"⚠️ **Agent Error**: {str(e)}"}

# === Build Graph ===
workflow = StateGraph(HealthAgentState)
workflow.add_node("retrieve_guidelines", retrieve_guidelines)
workflow.add_node("generate_report", generate_report)
workflow.set_entry_point("retrieve_guidelines")
workflow.add_edge("retrieve_guidelines", "generate_report")
workflow.add_edge("generate_report", END)

health_agent = workflow.compile()

# === Public API ===
def run_agent(
    patient_summary: str, risk_score: float, prediction_label: str, 
    prediction_confidence: float, groq_api_key: str
) -> str:
    initial_state = {
        "patient_summary": patient_summary,
        "risk_score": risk_score,
        "prediction_label": prediction_label,
        "prediction_confidence": prediction_confidence,
        "groq_api_key": groq_api_key,
        "retrieved_guidelines": [],
        "health_report": None,
    }
    final_state = health_agent.invoke(initial_state)
    return final_state.get("health_report", "Report generation failed.")

# === Chat API ===
CHAT_PROMPT = ChatPromptTemplate.from_messages([
    ("system", """You are a knowledgeable and empathetic AI health support assistant.
CRITICAL RULES:
1. Only make claims that are supported by the provided guidelines.
2. Answer the user's question directly based on their health context and retrieved guidelines.
3. Be concise and clear.
4. Always recommend consulting a healthcare professional for specific medical decisions.
5. STRICT GUARDRAIL: You are strictly a Diabetes and Health Assistant. If the user asks ANY question outside of health, diabetes, wellness, or the provided report (such as writing code, math, history, or unrelated topics), you MUST refuse to answer and say: "I am a specialized health assistant. I can only answer questions related to your diabetes risk assessment and health guidelines." Do not attempt to fulfill non-medical requests under any circumstances."""),
    ("human", """
## Patient Context
- **Risk Score**: {risk_score:.1f} / 100
- **Patient Profile**: {patient_summary}

## Retrieved Medical Guidelines 
{guidelines_text}

## Chat History
{chat_history}

## User Question
{user_question}
""")
])

def run_chat(
    user_question: str,
    chat_history: str,
    patient_summary: str,
    risk_score: float,
    prediction_label: str,
    groq_api_key: str
) -> str:
    """
    Public interface to handle conversational follow-ups.
    """
    try:
        # Retrieve context for new question
        embeddings = HuggingFaceEmbeddings(model_name=EMBED_MODEL)
        vectorstore = Chroma(persist_directory=CHROMA_DB_PATH, embedding_function=embeddings)
        results = vectorstore.similarity_search(user_question, k=3)
        guidelines_text = "\n\n---\n\n".join([doc.page_content for doc in results]) if results else "No specific guidelines retrieved."

        # Generate response
        llm = ChatGroq(model=LLM_MODEL, temperature=0.3, groq_api_key=groq_api_key)
        chain = CHAT_PROMPT | llm
        
        response = chain.invoke({
            "risk_score": risk_score,
            "patient_summary": patient_summary,
            "guidelines_text": guidelines_text,
            "chat_history": chat_history,
            "user_question": user_question,
        })
        return response.content
    except Exception as e:
        return f"⚠️ **Chat Error**: {str(e)}"
